version: '3'
services:

  db: 
    image: mongo
    # restart: always

  afa:
    build: afa
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./afa:/myapp:rw
    ports:
      - "3002:3000"
    
    depends_on: 
      - db
